server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: rating-service
          uri: lb://RARINGSERVUICE   # must match Eureka EXACTLY
          predicates:
            - Path=/ratings/**

        - id: hotel-service
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /staffs/**

  config:
    import: optional:configserver:http://localhost:8085